{
    authors_and_ratings(func: ge(rating, 4.0)) {
        author_name
        published @filter(lt(dislikes, 10)) {
            title
            likes
            dislikes
            tagged {
                tag_name
            }
        }
    }
}